version: '3.4'

services:
  docto:
    image: docto
    build:
      context: ..
      dockerfile: ./demo/Dockerfile
    volumes:
      - ./volume:/volume
      - ./front:/demo/front
    ports:
      - 8000:8000
